import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { dmSans } from "./fonts";

export const metadata: Metadata = {
  title: "Centro Medico Agliana",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning lang="en" className={dmSans.className}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
